### ISSUE TITLE
Biopython dependency problem (ModuleNotFoundError: No module named 'Bio.Data.SCOPData')

### ISSUE THREAD

**Issue by amsubramanian** [martinez-zacharya/TRILL#32]
Running any `trill` command in an environment with the latest `biopython` release (1.82) throws the following error:

```
Traceback (most recent call last):
  File "/home/arjuna/micromamba/envs/trill/bin/trill", line 5, in <module>
    from trill.trill_main import cli
  File "/home/arjuna/micromamba/envs/trill/lib/python3.10/site-packages/trill/trill_main.py", line 32, in <module>
    from trill.utils.dock_utils import perform_docking, fixer_of_pdbs, write_docking_results_to_file
  File "/home/arjuna/micromamba/envs/trill/lib/python3.10/site-packages/trill/utils/dock_utils.py", line 15, in <module>
    from biobb_vs.utils.box import box
  File "/home/arjuna/micromamba/envs/trill/lib/python3.10/site-packages/biobb_vs/utils/box.py", line 11, in <module>
    from biobb_vs.utils.common import check_input_path, check_output_path, get_box_coordinates
  File "/home/arjuna/micromamba/envs/trill/lib/python3.10/site-packages/biobb_vs/utils/common.py", line 15, in <module>
    from Bio.Data.SCOPData import protein_letters_3to1 as prot_one_letter
ModuleNotFoundError: No module named 'Bio.Data.SCOPData'
```
It appears that ([doc link](https://biopython.org/docs/1.81/api/Bio.Data.SCOPData.html)) `Bio.Data.SCOPData` was removed from `biopython` beginning with version 1.82. A workaround is to downgrade `biopython` (e.g. by `pip install biopython==1.81`) after completing all other setup instructions, but *this should probably be addressed as a dependency.*

**Comment by martinez-zacharya** [comment]
Thank you, this has been addressed in 1.5.3!
