### ISSUE TITLE
Finetuning ProtGPT2 error

### ISSUE THREAD

**Issue by vinerya** [martinez-zacharya/TRILL#8]
after finetuning protgpt2 and trying to generate, I get the following:
`Global seed set to 123
Traceback (most recent call last):
  File "/usr/local/bin/trill", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/trill/trill_main.py", line 385, in cli
    main(args)
  File "/usr/local/lib/python3.8/dist-packages/trill/trill_main.py", line 264, in main
    model = model.load_from_checkpoint(args.preTrained_model, strict = False)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/core/saving.py", line 139, in load_from_checkpoint
    return _load_from_checkpoint(
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/core/saving.py", line 188, in _load_from_checkpoint
    return _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/core/saving.py", line 234, in _load_state
    obj = cls(**_cls_kwargs)
TypeError: __init__() missing 1 required positional argument: 'lr'`

**Comment by martinez-zacharya** [comment]
Thank you so much, I fixed this bug in the latest release and now you should be able to use finetuned protgpt2 models!
